# Generated by Django 2.2.4 on 2020-07-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsproj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsproject',
            name='github_link',
            field=models.CharField(default='DEFAULT', max_length=300),
        ),
    ]
