# Generated by Django 2.2.4 on 2020-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200417_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github_link',
            field=models.CharField(default='DEFAULT', max_length=300),
        ),
    ]
