# Generated by Django 2.2.4 on 2020-07-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='github_link',
            field=models.CharField(default='#', max_length=300),
        ),
    ]
