# Generated by Django 2.2.4 on 2020-08-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pyproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('summary', models.CharField(max_length=255)),
                ('github_link', models.CharField(default='#', max_length=300)),
            ],
        ),
    ]
